[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    'hardhat/=node_modules/hardhat/',
    'solmate/=node_modules/solmate/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config